name: kluber
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.7.0
  http: ^1.2.0
  intl: ^0.19.0
  sqflite: ^2.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.2.2
  flutter_treeview: ^1.0.7+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
